if (can_anim == 1)
    anim += 0.3
draw_sprite(spr_gb_cover1, 0, (camera_x + 34), camera_y)
draw_sprite(spr_gb_cover2, 0, (camera_x + 34), (camera_y + 206))
draw_sprite(gb_head, anim, (camera_x + 94), camera_y)
draw_set_font(global.font_google)
draw_text_color((camera_x + can_x), (camera_y + 6), string_hash_to_newline((cantidad + "/90")), c_cont, c_cont, c_cont, c_cont, 1)
draw_sprite(spr_guardabot_tabs, 0, (camera_x + 34), (camera_y + 30))
draw_set_color(c_white)
draw_text((camera_x + 176), (camera_y + 32), string_hash_to_newline(gb_text_level))
