draw_sprite(spr_letters_super, 1, (camera_x + 96), (camera_y + 36))
draw_sprite(spr_letters_white, 0, (camera_x + 96), (camera_y + 57))
draw_sprite(spr_letters_white, 1, (camera_x + 119), (camera_y + 57))
draw_sprite(spr_letters_white, 2, (camera_x + 138), (camera_y + 57))
draw_sprite(spr_letters_white, 3, (camera_x + 157), (camera_y + 57))
draw_sprite(spr_letters_white, 4, (camera_x + 165), (camera_y + 57))
draw_sprite(spr_letters_white, 4, (camera_x + 165), (camera_y + 57))
draw_sprite(spr_letters_white, 0, (camera_x + 195), (camera_y + 57))
draw_sprite(spr_letters_white, 1, (camera_x + 218), (camera_y + 57))
draw_sprite(spr_letters_white, 5, (camera_x + 237), (camera_y + 57))
draw_sprite(spr_letters_white, 6, (camera_x + 256), (camera_y + 57))
draw_sprite(spr_letters_white, 2, (camera_x + 273), (camera_y + 57))
draw_sprite(spr_we, 1, (camera_y + 214), (camera_y + 90))

