draw_set_font(global.font_google)
draw_set_color(c_letter)
draw_set_alpha(alpha)
var offset = 26
draw_set_halign(fa_center)
// no string here has hashes, plus it doesn't support newlines anyway, so :)
draw_text(x_pos, ((y + offset) - yy), "SUPER MARIO MAKER WORLD ENGINE | 2019 - 2023");
offset += 24;
draw_text_color(x_pos, ((y + offset) - yy), lang().credits.programmers, c_title, c_title, c_title, c_title, alpha);
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Franyer Farías");
offset += 24;
draw_text_color(x_pos, ((y + offset) - yy), lang().credits.sfx, c_title, c_title, c_title, c_title, alpha);
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "DangerousZone");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Julia");
offset += 24;
draw_text_color(x_pos, ((y + offset) - yy), lang().credits.spriters, c_title, c_title, c_title, c_title, alpha);
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Danny Sliverd");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "EmaxCapoYT");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Francozkai29");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Isaías");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "JoaDash");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Julia");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Keira");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "LucasGamer");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "MauroGRF");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Mega Mario Bros 789");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "NANO");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Nintenderos Android");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Policombo");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "TheMaker");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "!z014yfsi_");
offset += 24;
draw_text_color(x_pos, ((y + offset) - yy), lang().credits.animations_fx, c_title, c_title, c_title, c_title, alpha);
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Isaías");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Julia");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Tokarev");
offset += 24;
draw_text_color(x_pos, ((y + offset) - yy), lang().credits.fonts, c_title, c_title, c_title, c_title, alpha);
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Aseprite");
offset += 24;
draw_text_color(x_pos, ((y + offset) - yy), lang().credits.additional, c_title, c_title, c_title, c_title, alpha);
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Alexader R.");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Angela Gonzales");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Endood");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Gabriel Gamer 2.0");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Gatu's");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "iDomi");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "MatheusGamer");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Med Animations");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Nicolas Peixoto");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "TheMario");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "¡TraxerGames");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "WillyMaker");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Zaid Eduardo");
offset += 24;
draw_text_color(x_pos, ((y + offset) - yy), lang().credits.special_thanks, c_title, c_title, c_title, c_title, alpha);
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "AlexisJR");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Androacks22");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Anndy Mike");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "DangerousZone");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Francozkai29");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Gabs");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Gatete");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "iDomi");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Jeanyer");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Julia");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Lilistalker");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "MauroGRF");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Winter");
offset += 24;
draw_text_color(x_pos, ((y + offset) - yy), lang().credits.powered_by, c_title, c_title, c_title, c_title, alpha);
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Gatete Mario Engine");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Hello Mario Engine");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Mario Worlds Delta");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Unimaker");
offset += 24;
draw_text_color(x_pos, ((y + offset) - yy), "Game Forever | Enginer Dev Team", c_title, c_title, c_title, c_title, alpha);
offset += 24;
draw_text_color(x_pos, ((y + offset) - yy), lang().credits.programmers, c_title, c_title, c_title, c_title, alpha);
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Andoyt");
offset += 24;
draw_text_color(x_pos, ((y + offset) - yy), lang().credits.spriters, c_title, c_title, c_title, c_title, alpha);
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Kike19");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "NaNo");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Apolos");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Suil");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Urikett");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "NoobTime");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "David Nintenplay");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Andoyt");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Varnat");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Cupaban");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Mega Mario Bros 789");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Gatuping");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Nameless");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "HeXp");
offset += 24;
draw_text_color(x_pos, ((y + offset) - yy), lang().credits.translators, c_title, c_title, c_title, c_title, alpha)
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Vini");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Nameless");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Andoyt");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "NicoplaysZ");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "GustaSaiyajin06");
offset += 24;
draw_text_color(x_pos, ((y + offset) - yy), lang().credits.additional, c_title, c_title, c_title, c_title, alpha)
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Nemiad");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Varnat");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Sicraft");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Les");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "DangerousZone");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "TheWatermelon24");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "New-Drago");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Polartic");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Kass");
offset += 24;
draw_text_color(x_pos, ((y + offset) - yy), lang().credits.special_thanks, c_title, c_title, c_title, c_title, alpha)
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Sicraft");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "MarioFranyer");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Nemiad");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Gatuping");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "HeXp");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Varnat");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "New-Drago");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "DangerousZone");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Les");
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "Polartic");
offset += 24;
draw_text(x_pos, ((y + offset) - yy), "SuperWE Dev Team");
offset += 24;
draw_text_color(x_pos, ((y + offset) - yy), lang().credits.programmers, c_title, c_title, c_title, c_title, alpha);
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "NCubs");
offset += 24;
draw_text_color(x_pos, ((y + offset) - yy), lang().credits.spriters, c_title, c_title, c_title, c_title, alpha);
offset += 12;
draw_text(x_pos, ((y + offset) - yy), "NCubs");
offset += 24;
draw_text(x_pos, ((y + offset) - yy), string(lang().credits.and_you, global.name_user ?? ""));
offset += 24;

draw_set_halign(fa_left);
draw_sprite(spr_NSMBU_mario_small_walk, index, 240, ((y + offset) - yy));
draw_sprite(spr_NSMBU_luigi_walk, index, 208, ((y + offset) - yy));
draw_sprite(spr_NSMBU_toad_small_walk, index, 176, ((y + offset) - yy));
draw_sprite(spr_NSMBU_toadette_walk, index, 144, ((y + offset) - yy));
offset += 48;
draw_set_halign(fa_center);
draw_sprite(spr_emilio, index, 176, ((y + offset) - yy));


